### ISSUE TITLE
Incompatibility with AMP pages

### ISSUE THREAD

**Issue by ronalfy** [Angrycreative/bj-lazy-load#20]
Just making you aware, but the plugin doesn't play nicely with the new AMP plugin by WordPress: https://wordpress.org/plugins/amp/

Recommend just disabling the plugin on /amp/ output.

**Comment by tobaco** [comment]
You can add the following action to your functions.php to disable the plugin for the amp output:

```
	function bjll_compat_amp() {
		if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
			add_filter( 'bjll/enabled', '__return_false' );
		}
	}

	add_action( 'bjll/compat', 'bjll_compat_amp' );
```

**Comment by ronalfy** [comment]
Awesome! Thanks for the snippet!

**Comment by ankshvayt** [comment]
@tobaco Thanks for the snipppet! :)

**Comment by shaneonabike** [comment]
Would it be possible in the configuration just to add a checkbox that allows us to turn it off for AMP which is selected automatically. It took me a while before I was able to determine that this was actually the issue :/

**Comment by jan-san** [comment]
Lazy loading was deactivated for AMP pages in v1.0.8.
