### ISSUE TITLE
Compatibility with BadgeOS

### ISSUE THREAD

**Issue by rohitmanglik** [Angrycreative/bj-lazy-load#21]
I am using BJ Lazy Load (v1.0.6) and when I tried to activate BadgeOS, I received following error:

Fatal error: Cannot redeclare class BJLL_AdminPage in /{site-address}/wp-content/plugins/bj-lazy-load/inc/class-bjll-adminpage.php on line 77

After further digging out I found that both use some copies of https://github.com/scribu/wp-scb-framework and for some reason, it seems like the BJLL class is being loaded twice somehow.

Wrapping the class in question in if ( ! class_exists( 'BJLL_AdminPage' ) ) { ... } helped with my local install. 

Regrading the SCB Framework part, I don't know about it enough to debug _why_ it's happening.

Can we have this change in future release?

**Comment by jan-san** [comment]
This was fixed in v1.0.7
