### ISSUE TITLE
Support for image specific placeholders

### ISSUE THREAD

**Issue by deas** [Angrycreative/bj-lazy-load#26]
The current implementation only supports one placeholder for all images. User experience (and Google Pagespeed scoring "above the fold" ;)) could be improved by supporting image specific placeholders. [Gif placeholder 64base encoded generator for WordPress images + Lazysizes.js](https://medium.com/@mosne/dynamic-64base-encoded-gif-placeholder-for-wordpress-images-lazysizes-js-2261f466037a#.4tzk15afo) outlines a clever approach. Would be awesome if we could introduce this functionality to BJ Lazy Load.

**Comment by jan-san** [comment]
Image-specific placeholders have been added to the plugin in the meantime.
