### ISSUE TITLE
Images not getting loaded when accessed website via android webview or from chrome mobile view

### ISSUE THREAD

**Issue by techirsh** [Angrycreative/bj-lazy-load#28]
I am working on woocommerce site. I have used this plugin for lazy load. Images gets loaded when in normal view. when i am looking the same site in responsive view using the inspect element in cheome browser. Images are not loaded when scrolled. testing link http://labs.techirsh.com/mvsstore/shop/

![image](https://cloud.githubusercontent.com/assets/2632195/21501814/313e6320-cc71-11e6-922e-98598e0f323d.png)

**Comment by jan-san** [comment]
I cannot reproduce this issue, and the demo shop is no longer online.
Please reopen this ticket if the issue persists with the latest version of the plugin.
