### ISSUE TITLE
pictures are'nt loaded with amp plugin

### ISSUE THREAD

**Issue by seraphyn** [Angrycreative/bj-lazy-load#30]
Pictures are not shown with the amp-plugin by automattic ( https://de.wordpress.org/plugins/amp/)

Wrong displayed coee is 
`<div class="amp-wp-article-content">
		<p><amp-img class="lazy lazy-hidden alignnone wp-image-1257 size-full amp-wp-enforced-sizes" src="data:image/gif;base64,R0lGODdhAQABAPAAAP///wAAACwAAAAAAQABAEACAkQBADs=" alt="Nice Pictrue width="1280" height="556" sizes="(min-width: 800px) 800px, 100vw"></amp-img></p><br/>`

**Comment by jan-san** [comment]
The issue has been fixed in v1.0.8
