### ISSUE TITLE
Tiny image sizes created

### ISSUE THREAD

**Issue by brit77** [Angrycreative/bj-lazy-load#32]
I recently found that BJ Lazy Load is creating a 30 x ~20px image size for each upload since late 2016. Is this on purpose? I can't find why this is happening or how to disable it.

**Comment by kaalis** [comment]
/wp-content/plugins/bj-lazy-load/bj-lazy-load.php:
add_image_size( 'tiny-lazy', 30, 30 );

Happens because of this code, don't know why it's needed.

**Comment by AronTornberg** [comment]
Hi,

The image size is used for the low-res preview image feature. We will look into making this optional.

**Comment by brit77** [comment]
Version 1.0.9 appears to have removed the tiny image size as per the changelog. I used the Force Regenerate Thumbnails plugin to remove these unneeded thumbnails. So, thanks...this appears to be resolved!

Final question:
The changelog says the tiny thumbnails are created only when low-res preview image is used. When are low-res preview images called for?

**Comment by jan-san** [comment]
With low-res preview images, it's possible to first show a blurry version of the image which transitions into the full resolution picture - you can see this effect in any [Medium article](https://medium.com/walmartlabs/lazy-loading-images-intersectionobserver-8c5bff730920).
