### ISSUE TITLE
Issue on loading content on www.marcoborla.it - Blank image on loading…

### ISSUE THREAD

**Issue by PeopleInside** [Angrycreative/bj-lazy-load#33]
Hi,
I hope the issue can be solved soon. This plug-in is great and are working fine on my other two website
https://www.peopleinside.it and https://blog.peopleinside.it

BUT is not working well on http://www.marcoborla.it
as is showing a blank image on the loading also if I select the options to Use low-res preview image.
![1](https://cloud.githubusercontent.com/assets/5006150/25743508/10bef522-3195-11e7-9543-681c38a3ef8c.png)

I created a WordPress support topic here:
https://wordpress.org/support/topic/blank-image-on-loading/

During the loading process the website is showed badly:
![2](https://cloud.githubusercontent.com/assets/5006150/25743618/7e0d4d54-3195-11e7-8d70-5c37f1140ea7.png)

after the load process is showed correctly:
![3](https://cloud.githubusercontent.com/assets/5006150/25743634/93043eca-3195-11e7-87ff-91fd63b3a668.png)

I also tried to put a custom image loading but this will not work because if in the homepage all content are loaded if I clock on blog with custom loading image will be showed loading image instead images and videos.

**Comment by AronTornberg** [comment]
Hi,

The low res image feature uses a custom image size. Thus if for it to work with images created before the feature was added the image sizes need to be regenerated. This can be done with a pluign such as this: https://wordpress.org/plugins/regenerate-thumbnails/

WE will look into making this clearer and possible adding the feature to the plugin itself.

**Comment by jan-san** [comment]
A notice has been added in 8859b5128e01b678b5c5b94cda218d3afabdd674
