### ISSUE TITLE
Breaks image with 'sizes' in its name

### ISSUE THREAD

**Issue by PallasKatze** [Angrycreative/bj-lazy-load#35]
This line breaks image with word `sizes` in its name:

https://github.com/Angrycreative/bj-lazy-load/blob/c8146b7b24472481534c976592700203da5070ea/inc/class-bjll.php#L219

`social-media-image-sizes_700x350.jpg` -> `social-media-image-data-lazy-sizes_700x350.jpg`

**Comment by rickard-berg** [comment]
This was fixed in #52 instead.

Closing.
