### ISSUE TITLE
Do not want to lazy load images above the fold

### ISSUE THREAD

**Issue by pallavic27** [Angrycreative/bj-lazy-load#38]
Hi,

Is there any way I can automatically skip above the fold images from being lazy loaded ? I have a page which displays lot of WooCommerce products. All images are getting the lazy load class. I want that above the fold image shoi;d not get lazy loaded. Also I noticed that lazy loading is not working on WooCommerce single product page. Is this a bug ?

**Comment by bjornjohansen** [comment]
There is no way the server can know where the fold is, so this is not possible, no.
