### ISSUE TITLE
Update scb framework

### ISSUE THREAD

**Issue by dikiyforester** [Angrycreative/bj-lazy-load#39]
Hello!

Could you update the scb framework instance?

Currently we've got a conflict since our themes also includes it. Themes include version 60, plugin includes  version [58](https://github.com/Angrycreative/bj-lazy-load/blob/master/inc/scb/load.php#L3). 
Plugin loads its version first, theme uses it and get version incompatibility issues.

If you update the scb framework instance in the plugin to latest version we'll avoid this issue.

Thank you very much!

**Comment by Alir3z4** [comment]
I'm having the similar issue.
