### ISSUE TITLE
Option to lazy load on window.load or idle time

### ISSUE THREAD

**Issue by 2aces** [Angrycreative/bj-lazy-load#40]
It would great to have an option to which allow images to be loaded after the whole page is loaded, of X seconds after loading or idle time. It would allow images to be loaded when the user is reading above the fold, for example. 

In the future, maybe even conditionally load images based on [Navigator.online](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events) property and/or [Network API](https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API)

This could be either an option in the admin or a hook.

PS: Creating this issue to gather opinions, ideas, and to track the development/PR, which will work on next month.

**Comment by bjornjohansen** [comment]
You can this yourself in a script that calls `BJLL.show( el )` where `el` is the element you want to show.
