### ISSUE TITLE
Adding filter for custom themed site

### ISSUE THREAD

**Issue by Light1c3** [Angrycreative/bj-lazy-load#42]
Sorry for the easy question, but how would I add the PHP code so that this works with a custom theme?

**Comment by bjornjohansen** [comment]
For images in the content, you don’t have to do anything.

For images not in the content field, you have to filter the HTML for the image through `bj_lazy_load_html`.

**Comment by Light1c3** [comment]
Thank you for getting back to me so quickly! The website uses SiteOrigin for the template, and after testing the lazy loading doesn't work out of the box. I'm not sure what I should be doing to filter the HTML through `bj_lazy_load_html`

**Comment by Light1c3** [comment]
This is the site in question: https://palermophoto.com/
