### ISSUE TITLE
Not working with "CloudFlare Cache Everything"

### ISSUE THREAD

**Issue by MKDan** [Angrycreative/bj-lazy-load#45]
I'm using BJ Lazy Load for lazy loading images on my WordPress blog and another plugin for lazyloading comments. My website is fully cached by CloudFlare. The Comments are lazy loading but the images (BJ Lazy Load) is not working.

**Comment by chinmayrajyaguru** [comment]
> I'm using BJ Lazy Load for lazy loading images on my WordPress blog and another plugin for lazyloading comments. My website is fully cached by CloudFlare. The Comments are lazy loading but the images (BJ Lazy Load) is not working.

First, Uncheck `HTML` cache from CloudFlare through `Speed > Auto Minify`. Re-test after clearing cache from CloudFlare and cache plugin.

I hope this might help you.

**Comment by jan-san** [comment]
Closing this as the OP did not respond. Please reopen the issue with a link to site if the issue persists.
