### ISSUE TITLE
Problems with moving divs around

### ISSUE THREAD

**Issue by emumanu** [Angrycreative/bj-lazy-load#9]
Hello,

first thank you for this great plugin. I have a page with a lot of divs, and each one has an image. If the divs don't change their positions, everything works ok. However, I have a dropdown to filter the items to show, and when I select a filter, the divs change their position, and some times the images don't get displayed. 

Probably that repositioning makes the sonar stuff to fail. Is there anything I could do to have your plugin working in that scenario?

Thank you

**Comment by jan-san** [comment]
This was addressed in b360afdc7517e969f72e180a423bdfe4ad2bb971 - the plugin now checks for newly visible images continuously (even when there was no scrolling), so the images in the moved divs will be picked up now.
